### ISSUE TITLE
In hand

### ISSUE THREAD

**Issue by Elijeh** [PlaceholderAPI/CheckItem-Expansion#1]
It'd be handy to have a modifier to check if the player is holding said item(s) in their hand.

**Comment by aBo0oDyy** [comment]
You can do that with [Javascript expansion](https://api.extendedclip.com/expansions/javascript/) using `%player_item_in_hand%` placeholder from [Player expansion](https://api.extendedclip.com/expansions/player/).
Maybe you'd only need the player placeholder if you're using that in a plugin that allows you to check multiple things. Like for example [DeluxeMenus](https://www.spigotmc.org/resources/deluxemenus.11734/)
