### ISSUE TITLE
Enchanted Books not working

### ISSUE THREAD

**Issue by ChrisWard316** [PlaceholderAPI/CheckItem-Expansion#10]
trying to check for a mending enchanted book:

/papi parse me %checkitem_mat:enchanted_book,enchantments:Mending%

this returns no but i do have a mending enchantment book in my inventory.

PlaceholderAPI 2.10.6
Paper-284

**Comment by cj89898** [comment]
Possibly related to Enchantment#getName being deprecated. Will look into this.

**Comment by cj89898** [comment]
Fixed in v1.8.0
