### ISSUE TITLE
Suggest : NBT check

### ISSUE THREAD

**Issue by SskyWorms** [PlaceholderAPI/CheckItem-Expansion#11]
Can you add NBT check for CheckItem Expansion ? i have plugin can make custom nbt tag and using them for DeluxeMenus

**Comment by cj89898** [comment]
I don’t really know how NBT works sadly. I think it’s something to do with persistent data?

All I have support for right now is the custom model data.

**Comment by broken1arrow** [comment]
NBT work like a hashmap, you has value and key more or less (i think you have to first get the NBT tag, has not play too much with this (but I think it exist a getter for get the key for the item, but not i think you need to know the key)). :) 

Depending how it are implemented, is will stay so long you not place the item.

I look here and I think you need the key, I not think you can first get the key if not has key can fix that (if you want to add support I can try it out). 
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/metadata/Metadatable.html

**Comment by cj89898** [comment]
Structurally I understand NBT, just not how to implement it with code.

The docs you linked are for metadata, not for NBT data, as this will not persist.

**Comment by broken1arrow** [comment]
Was a quick seach (so can have send wrong link), but so long you not set nbt on players it should work. 

This a example i use, i has test this, I use a easy way to set the data.

```
			final ItemStack ItemOut = (new ItemStack(CHEST));
			ItemStack Itemmeta = CompMetadata.setMetadata(ItemOut, "CHEST", CHESTTYPEMETA);
			final ItemMeta var6 = Itemmeta.getItemMeta();
			ItemOut.setItemMeta(var6);
			HashMap ItemIfdropOrNot = player.getInventory().addItem(ItemOut)
```
