### ISSUE TITLE
Suggestion: commands

### ISSUE THREAD

**Issue by Tanguygab** [PlaceholderAPI/CheckItem-Expansion#13]
Hey, based on what you said [here](https://discordapp.com/channels/164280494874165248/164280494874165248/719208982530490469) x)
Could you add that command ? 👀  
`/checkitem remove <player> <modifier1> <modifier2> <modifier3> ...`
EDIT: actually, would be cool to have a 
`/checkitem give <player> <modifier1> <modifier2> <modifier3> ...` too =)

**Comment by Tradie18** [comment]
Yes please....

**Comment by cj89898** [comment]
remove was added in 1.9.0

**Comment by Tanguygab** [comment]
nice, thanks =)
should I close this ?

**Comment by Tanguygab** [comment]
Hey, apparently the remove placeholder doesn't work well with the amount =/ it removes all items instead of the defined amt:<number>

**Comment by Tradie18** [comment]
Cj has already said it's still an experimental build. Amount is not yet working.

**Comment by cj89898** [comment]
Closing this since amount was added. I don't have plans on adding a give command really.
