### ISSUE TITLE
Not removing single item

### ISSUE THREAD

**Issue by RoinujNosde** [PlaceholderAPI/CheckItem-Expansion#19]
I tried using this placeholder:
%checkitem_remove_mat:SKULL_ITEM,amt:1,data:3,namecontains:&a&lGema%

But it only removes if I have more than 1 item in my inventory.

**Comment by RoinujNosde** [comment]
The problem is on setting the item amount to 0. It's not supported on older Spigot versions (1.8.8 for example).

You should call Inventory#remove if the amount would be 0.

**Comment by cj89898** [comment]
I’m currently locked out of my GitHub account so this is from my email.

I found out the other day it fails to set amount to 0 and was asking around for a new method, will test with the remove method when I get home later.

**Comment by cj89898** [comment]
Fixed in 24eab997eaaecd0b02410080ddbff1140d56427f
