### ISSUE TITLE
1.16.4 Oright, some issues in your new version 2.0

### ISSUE THREAD

**Issue by broken1arrow** [PlaceholderAPI/CheckItem-Expansion#21]
If you set up placeholders wrongly, it spit out a error some is hard too read (I know is wrong,but I have set it wrong on purpose).

%checkitem_give_potiontype:NIGHT_VISION,amt:1,mat:potion,potionextended:false,potionupgraded:true%
https://pastebin.com/stTTqbpS
%checkitem_give_potiontype:SPEED,amt:1,mat:potion,potionextended:true,potionupgraded:true%
https://pastebin.com/KqZY4APp

**Comment by broken1arrow** [comment]
Before I forget, otherwise giving seems to work.

Maybe add lore (if possible), so maybe you can add your own text to the item (no need, but fun thing if possible)?

May also consider, how to apply this check in practice, because it comes with certain problems, if you have it as a requirement, it will be a problem if you have several requirements and this is first (then it gives the item first before it checks the rest).

**Comment by cj89898** [comment]
I was thinking of adding lore before release so I might do that. As for the invalid syntax I'm not sure if I'll do anything to stop the errors other than just warn the user in the documentation. I believe I take the same sort of approach with some other things like enchantments.

**Comment by broken1arrow** [comment]
I try your expansion in 1.9.4  (paper) and it work (but i only use command /papi parse), i not test all stuff but potion seams too work with potionextended and potionupgraded (only thing is the chat is more limit in 1.9, so you have to use shorter placeholders) . I think the console not has same limits (but has not try).

**Comment by broken1arrow** [comment]
Sry I´m not update you fast, has some other things too do :)

So I get bottom of this problem, seems to be as I said the famous bug where one in creative (seems to be mostly getting the error), where one gets gost block some cause this.

When I was in surval, the error was solved when I put things in them affected the slots, so I got two items that were missing. Is a really old version and probably the bug is more noticeable here.

**Comment by broken1arrow** [comment]
And if you miss it I test this command when I look in too this.

https://i.imgur.com/vGJef24.png

**Comment by cj89898** [comment]
Sounds pretty good, do you think it's ready for release then?

**Comment by broken1arrow** [comment]
I will give you more info tomorrow, but I can give you this this is what happen when you don´t have money, if your placeholder is first it give you the item first and check next requirement after (so you can get free items). I don´t know if this can be fix, it is way for example blizzz not recommend remove_ in requirement (he want more bulletproof, some he recommend to others). 

https://youtu.be/Vw9rKUU1rJE

**Comment by broken1arrow** [comment]
If you set it up like this, but if you flip it it work. 

https://paste.helpch.at/alibidawoq.bash even try Javascript https://paste.helpch.at/moxozehuxo.makefile

I know is hard to do something to stop this, but many some will use this, will set it up all different ways. I know you can use placeholders, but can you even put in economy in this?
