### ISSUE TITLE
Armor Slots

### ISSUE THREAD

**Issue by Sparxez** [PlaceholderAPI/CheckItem-Expansion#23]
Hello, using %checkitem_remove% while someone is wearing something as armor doesn't remove the item, instead checks for it and keeps it in there armor slot.

**Comment by cj89898** [comment]
Fixed in 2.0.4 https://github.com/PlaceholderAPI/CheckItem-Expansion/commit/2e4fabdc292ca5329a3280613f73cf1e96172db1
