### ISSUE TITLE
Placeholder to check if item inhand needs repair

### ISSUE THREAD

**Issue by Bloodlex** [PlaceholderAPI/CheckItem-Expansion#25]
Placeholder to check if item inhand needs repair

**Comment by cj89898** [comment]
Seems to work fine for me, what version are you on and how are you using it?

**Comment by Bloodlex** [comment]
> Works fine on 1.16.5 with both hands.
> 
> `%checkitem_mat:wooden_sword,inhand%`

How does it check if the item is broken?

**Comment by cj89898** [comment]
There won't be a way to do it with this expansion. If you use the player expansion you can use `%player_item_in_hand_data%` and it will return the data value so you can check if it's anything but 0 (meaning it needs repair).

**Comment by Bloodlex** [comment]
> There won't be a way to do it with this expansion. If you use the player expansion you can use `%player_item_in_hand_data%` and it will return the data value so you can check if it's anything but 0 (meaning it needs repair).

Thanks very much, it works! :)
