### ISSUE TITLE
Option to disable give and remove placeholders

### ISSUE THREAD

**Issue by Lukos31** [PlaceholderAPI/CheckItem-Expansion#26]
I've discovered that it's possible for the give and remove placeholders to be abused if a player can find a way to parse them. eg. allowing a player to set up a hologram that uses placeholders allows them to generate infinite items, or to clear an unsuspecting player's inventory with %checkitem_remove_%. (yes technically such a vulnerability would allow a knowledgeable attacker access to any placeholders, but it's a bigger problem here given that these ones actually make ingame changes when parsed)

An option to disable these placeholders would allow people to use this expansion who just want to check players if they have certain items.

**Comment by broken1arrow** [comment]
First of you should not give players access to hologram some create integration with the Holo.

I mean they can in theori run lots of deferent placeholders not only check item.

**Comment by Lukos31** [comment]
I use holograms only as an example of how it could be abused. Many plugins allow commands to involve placeholders, which is why this particular expansion poses a risk, since it's one of the only expansions to create permanent effects through parsing placeholders. An option to disable ones not needed allows use of this expansion without the risk

**Comment by cj89898** [comment]
I completely agree with @broken1arrow . I really don't see any use for common players to use placeholders.

**Comment by broken1arrow** [comment]
> I use holograms only as an example of how it could be abused. Many plugins allow commands to involve placeholders, which is why this particular expansion poses a risk, since it's one of the only expansions to create permanent effects through parsing placeholders. An option to disable ones not needed allows use of this expansion without the risk

I know at least on other placeholder expansion, some can be harmful too, So recommend you set up so players not can use placeholders.

I mean normal players not need papi parse for example and not let players has asses to hologram plugin some can parse commands and holo (not only placeholders are hurtful, if you set up your server wrong).

I mean most plugin has option to run commands as console/fakeop for example (something you can set in some holograms plugins too). 

Has not see yet, plugin without perms you can run placeholders thru commands or armor-stands/holo. So I recommend you check how you set up the perms on your server (and if you not have a permission plugin fix one).

**Comment by Lukos31** [comment]
> I completely agree with @broken1arrow . I really don't see any use for common players to use placeholders.

I agree, players should not have access to placeholders, however, it is extremely easy to find ways to parse placeholders if a server uses certain configurations/plugins. ordinarily this poses minimal problem, since placeholders cannot be used to make in game changes (which is perhaps why so many devs i’ve asked about this haven’t bothered to patch it). in the case of this extension, since changes can be made when parsing the placeholder itself it exacerbates the risk.

if it’s too much work/not worth your time i won’t keep bothering you, just thought it was a relatively simple addition that would allow us to keep using your expansion (it works extremely well for our purposes, but the issue of security is too large to ignore).

**Comment by cj89898** [comment]
As you said, it's really not much work to add it, so I did in v2.1.0 a06d1e34725e18208116fc53edb580237873d1c0
