### ISSUE TITLE
Suggest: In[armorslot, offhand]

### ISSUE THREAD

**Issue by ElTodoFull** [PlaceholderAPI/CheckItem-Expansion#27]
as there is inhand; checks such as inhelmet, inbreast, inpants, inboots and inoffhand, would be very useful.
That'd be much appreciated.

**Comment by cj89898** [comment]
Will most likely add something like this, might be a few weeks though.

**Comment by cj89898** [comment]
Added in a64f35d7e5ef40919386bdecd3a7a7db6518d5fa
