### ISSUE TITLE
we can not verify an amount greater than 64: /

### ISSUE THREAD

**Issue by D3BoxOfficiel** [PlaceholderAPI/CheckItem-Expansion#3]
Exemple:  %checkitem_mat:prismarine_shard,amt:96,nameequals:&3Fragment de Key% does not work if more than 64.

the same for this: %checkitem_mat:glass,amt:65%

A lot if it is possible to add this option would be really cool and nice!

**Comment by cj89898** [comment]
Definitely something I could look into

**Comment by cj89898** [comment]
Added in https://github.com/PlaceholderAPI/CheckItem-Expansion/commit/c493ac77685c31c476d228979c24d94744348fee
