### ISSUE TITLE
%checkitem_inhand% should have an option to pick either offhand, or mainhand

### ISSUE THREAD

**Issue by Maroon28** [PlaceholderAPI/CheckItem-Expansion#31]
Straightforward request. Instead of having %checkitem_inhand% check both the offhand & mainhand, instead we could have something like this:

%checkitem_inhand:main% will check the main hand

%checkitem_inhand:offhand% will check the offhand

%checkitem_inhand% will check both

**Comment by cj89898** [comment]
Added in 2.3.0 5e8e87716f2b479370cac57e8df6b0b388d9cc0a
