### ISSUE TITLE
%checkitem_remove% doesn't work on offhand

### ISSUE THREAD

**Issue by itslukemango** [PlaceholderAPI/CheckItem-Expansion#32]
As far as I can tell from testing, the %checkitem% placeholder works on offhand, but %checkitem_remove% does not.

What I tested: https://lukemango.com/dc4QK.png
It returns "yes" but doesn't remove it.

CheckItem Version 2.3.0
PAPI Version 2.10.9
Airplane 1.16.5 Version 4144b28

**Comment by cj89898** [comment]
Offhand does not work for the `give` modifier either. Will look into this soon.
