### ISSUE TITLE
Query NBT tags with the new nbtStrings placeholder

### ISSUE THREAD

**Issue by Darkhand81** [PlaceholderAPI/CheckItem-Expansion#43]
Hello!

Can you give an example of how to use the new nbtStrings to query an arbitrary NBT tag? I'm having trouble grokking how to get an NBT tag and use its value as a variable, instead of just comparing it against a known value.

Thanks!

**Comment by cj89898** [comment]
Currently there is no way to get the *raw* value, but you can use the `getinfo` placeholder with `nbtStrings` or `nbtInts` and it will return all nbt tags in a certain pattern. You could then use the javascript expansion to extract the value from there.

You can always get a ton of help for things  like this over on the [HelpChat Discord](https://helpch.at/discord)
