### ISSUE TITLE
modifier problem

### ISSUE THREAD

**Issue by 157946a** [PlaceholderAPI/CheckItem-Expansion#47]
https://github.com/PlaceholderAPI/PlaceholderAPI/issues/852

**Comment by cj89898** [comment]
Not sure if I quite understand the issue, but it looks like there is an extra space in your placeholder before `inhand` `%checkitem_mat:diamond_sword, enchantment:damage_all=1, inhand:main%`.

If you need more assistance it would be easier to converse on the [HelpChat Discord](https://helpch.at/discord)
