### ISSUE TITLE
nbtstrings: not working?

### ISSUE THREAD

**Issue by natr566** [PlaceholderAPI/CheckItem-Expansion#48]
MC 1.19
%checkitem_getinfo:mainhand_nbtstrings:% Dosent seem to work
and i used the example on the wiki
%checkitem_nbtstrings:PublicBukkitValues..executableitems:ei-id=Free_Money%
And changed it to
%checkitem_nbtstrings:PublicBukkitValues..oraxen:id=enchanted_pebble% And got just the placeholder not the result
%checkitem_amount_nbtstrings:PublicBukkitValues..oraxen:id=enchanted_pebble% And got just the placeholder not the result
![image](https://user-images.githubusercontent.com/29591762/177406053-e935a218-51e0-4deb-a9ad-24e2775732a6.png)

Maby im doing something wrong?

**Comment by cj89898** [comment]
Looks like you're testing it in some holographics plugin, if you need help with that head over to the [Helpchat Discord](https://helpch.at/discord).

Test placeholders with `/papi parse <player|me> <string>` for accurate testing.
