### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by xMateuszP0L** [PlaceholderAPI/CheckItem-Expansion#5]
Add:
-  Check amount of item in player inventory/enderchest.
- Check durability of item

**Comment by WarnDangerous** [comment]
Yeah it would be cool ! I also need this feature ( Check amount of item in player inventory ) :D

**Comment by aBooDyy** [comment]
Hey @xMateuszP0L,
I've just added the amount placeholder in my PR.
Please wait until it gets reviewed and then updated.

For the `Check durability of item`, 
I didn't quite understand what you want and for what and how would that work with multiple items. You can check the placeholder to get the durability of the item in your hand in [Player Expansion](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player) if that's what you want.
