### ISSUE TITLE
getinfo of enchantment should return 0 if it doesn't have it.

### ISSUE THREAD

**Issue by ElTodoFull** [PlaceholderAPI/CheckItem-Expansion#54]
It returns nothing, and that causes problems with plugins.

Thank you in advance!

**Comment by cj89898** [comment]
What placeholder are you using and what plugin is it breaking in?

**Comment by ElTodoFull** [comment]
> 

%checkitem_getinfo:mainhand_enchantments:Unbreaking%
That returns a number if the item has unbreaking, returns the level.
If it doesn't have the enchant, it returns a blank message, instead of 0.
That causes problems with conditional events, a plugin similar to Skript, since it doesn't get a number to compare with.

**Comment by cj89898** [comment]
Returns 0 now if enchantments don't exist. Still blank with air

**Comment by Clexus** [comment]
> %checkitem_getinfo:mainhand_enchantments:Unbreaking%
> That returns a number if the item has unbreaking, returns the level.
> If it doesn't have the enchant, it returns a blank message, instead of 0.
> That causes problems with conditional events, a plugin similar to Skript, since it doesn't get a number to compare with.

In fact it has a variable called %empty% that equals to a "blank"
