### ISSUE TITLE
Chelitem_getinfo with nbt not work for specific nbt

### ISSUE THREAD

**Issue by saildrag** [PlaceholderAPI/CheckItem-Expansion#55]
Hello,
With the placeholder %checkitem_getinfo:mainhand_nbtints:% I get the list of nbts. 

But I want to get the value of a specific nbt in my case that of "INTEGER:ae_enchantment;haste:3" And therefore get the number 3. 
The %checkitem_getinfo:mainhand_nbtints:ae_enchantment% displays the list of nbts. Same for %checkitem_getinfo:mainhand_nbtints:ae_enchantment=% / %checkitem_getinfo:mainhand_nbtints:ae_enchantment=haste% / %checkitem_getinfo:mainhand_nbtints:ae_enchantment=1%

**Comment by ElTodoFull** [comment]
Agree, but not only with enchants. I'd also like to get the "RepairCost" of the nbt of the item
![image](https://user-images.githubusercontent.com/22697982/207365485-8bd8ed13-d343-4d1c-94d6-2abc0651cdc6.png)
hoping for that to return 100000 instead of all the nbtints.

**Comment by cj89898** [comment]
Ex: `%checkitem_getinfo:mainhand_nbtints:CustomModelData=0%` would return `43010`
:)
