### ISSUE TITLE
Ability to specify modifier that decides whether or not output should be returned

### ISSUE THREAD

**Issue by CDFN** [PlaceholderAPI/CheckItem-Expansion#57]
This is specifically useful for add/remove actions. In my use case the text is always displayed as there's no way to disable it. It'd be great if we could silently add/remove items, so empty string would be returned from placeholder.
I'd imagine it as: `%checkitem_remove_mat:COAL,amt:10,nooutput%`

**Comment by cj89898** [comment]
This should be done with something like the changeoutput expansion to change the output to an empty string. If you need assistance, visit the [HelpChat Discord](https://helpch.at/discord)
