### ISSUE TITLE
lorecontains/loreequals not working properly?

### ISSUE THREAD

**Issue by Kristopherrr** [PlaceholderAPI/CheckItem-Expansion#58]
So basically for example when i use the `%checkitem_getinfo:mainhand_lorecontains:1%` placeholder it is supposed to return only the 2nd line of the item but instead it returns all the lores in a lore. In the screenshot, there are 2 different items from 2 different plugins
first one with the `&4test` in it its from Executableitems and the 2nd one is from ecoitems. The checkitem expansion version that i use is 2.6.8

![Screenshot 2023-04-20 174907](https://user-images.githubusercontent.com/114158743/233403591-076c19c9-b3a6-483c-b95f-7a02742672cb.png)

**Comment by cj89898** [comment]
Tested on 1.19.3 mc, seemed to work fine for me.

**Comment by Kristopherrr** [comment]
even if i do `%checkitem_getinfo:mainhand_lorecontains:1000%` i still get the same result

**Comment by Kristopherrr** [comment]
![image](https://user-images.githubusercontent.com/114158743/233693447-d8a82740-49df-4b12-a578-2f870c2b4511.png)
[using spigot]

**Comment by cj89898** [comment]
Old version was being used. Version shown in pictures above was from `/papi ecloud info checkitem` for anybody wondering.
