### ISSUE TITLE
Lore line missing letters

### ISSUE THREAD

**Issue by Foxagone** [PlaceholderAPI/CheckItem-Expansion#59]
When using %checkitem_getinfo:mainhand_loreequals:(number)%, it returns the lore line without the last letter.

**Example:**
![image](https://github.com/PlaceholderAPI/CheckItem-Expansion/assets/66205295/1330f021-cdcb-410e-9641-ea2312b06942)
_Item with lore (i tried different methods of adding the lore to the item, the issue was still the same)_

![image](https://github.com/PlaceholderAPI/CheckItem-Expansion/assets/66205295/9ddcdd9d-f91a-4fa1-bd5d-8e6f77f30ae7)
_Parsing the placeholder outputs the line without the last letter_

**Comment by cj89898** [comment]
I will take a look when I get home. I think I know why it happens.

Just to be sure, are you using the latest checkitem version?
