### ISSUE TITLE
Wrong amounts for give/remove placeholders

### ISSUE THREAD

**Issue by kristophergeou** [PlaceholderAPI/CheckItem-Expansion#64]
So, every time i try to give a user an item eg. `%checkitem_give_mat:TORCH,amt:1%` that `amt:` value is `*` by `3` so if i do `%checkitem_give_mat:TORCH,amt:2%` it will give `6`, `%checkitem_give_mat:TORCH,amt:3%`  will give `9`.

The same issue happens with the `%checkitem_remove_mat:TORCH,amt:2%` it will `*` by `3` and it will take `6` instead of `2.` Only these two placeholders seem to have that issue, the rest are fine

~ CheckItem Expansion: 2.7.2
~ Server: Paper-318 (MC: 1.20.2)

**Comment by cj89898** [comment]
Tested on 1.20.2 and 1.20.4 spigot, no issues at all.
