### ISSUE TITLE
Amount Modifier Hates 3s

### ISSUE THREAD

**Issue by mercurialmusic** [PlaceholderAPI/CheckItem-Expansion#72]
Hello! There seems to be a strange issue with the amount modifier which we ran into when testing with the remove modifier (I know), where any amount provided worked fine EXCEPT any value beginning with a 3. In these cases when amt:3 or amt:30 etc. all matching items were removed regardless of amount specified. Adding a 0 in front, e.g. amt:03 or amt:030 works as intended. 

Using CheckItem 2.7.5 on PAPI 2.11.6 on git-Paper-497 (MC: 1.20.4).

Thanks!

**Comment by cj89898** [comment]
Tested on 1.20.4, Checkitem 2.7.5, PAPI 2.11.6, using spigot. No issues
