### ISSUE TITLE
custom_data specific Item Component in 1.21 missing

### ISSUE THREAD

**Issue by Tidal-Flame** [PlaceholderAPI/CheckItem-Expansion#73]
Hi I don't know if this is still active but I'm getting no reply on the helpchat discord.

In the 1.21 upated expansion it seems the minecraft:custom_data item component was omitted. This component contains the PublicBukkitValues tag and all the custom data that other plugins tend to add. This is an absolutely vital component 

In this picture we have the comparison between /data for SelectedItem and %checkitem_getinfo:mainhand% 
![billede](https://github.com/user-attachments/assets/9cc1832c-86bd-46ef-a82f-504a536251c4)

**Comment by cj89898** [comment]
I believe this has been fixed in latest version.

**Comment by Tidal-Flame** [comment]
testing if this will re-open with a new message cause error about to be reported
